<template>
  <div class="text-white pt-7 relative bg-gradient-to-br from-gray-900 to-gray-800">
    <Navbar />
    <HeroSection />
    <FeatureSection />
    <ContentAutomationStats />
    <CallToAction />
    <TestimonialsSection />
    <Faq :faqs="faqs1" />
    <Footer />
  </div>
</template>

<script setup>
import { useHead } from '#imports'
import TestimonialsSection from '~/components/TestimonialsSection.vue'

const faqs1 = ref([
  { question: 'What is a copy?', answer: 'A copy refers to written content used for marketing or advertising purposes.' },
  { question: 'Does CopyGen write long articles?', answer: 'Yes, CopyGen can generate long-form articles based on your requirements.' },
  { question: 'Is the generated content original?', answer: 'Yes, all content generated by CopyGen is unique and plagiarism-free.' },
  { question: 'Do you have a WordPress plugin?', answer: 'Yes, we offer a WordPress plugin for easy integration.' }
])

// Set SEO metadata
useHead({
  title: 'AppName - AI-Powered Content Automation',
  meta: [
    { name: 'description', content: 'Generate high-quality marketing copy, blog posts, and SEO content effortlessly with CopyGen AI.' },
    { property: 'og:title', content: 'CopyGen - AI-Powered Content Automation' },
    { property: 'og:description', content: 'Generate high-quality marketing copy, blog posts, and SEO content effortlessly with CopyGen AI.' },
    { property: 'og:image', content: '/copygen-preview.png' },
    { property: 'og:url', content: 'https://yourwebsite.com' },
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: 'CopyGen - AI-Powered Content Automation' },
    { name: 'twitter:description', content: 'Generate high-quality marketing copy, blog posts, and SEO content effortlessly with CopyGen AI.' },
    { name: 'twitter:image', content: '/copygen-preview.png' }
  ]
})
</script>
